import {
  DemoUser,
  Clinic,
  Client,
  FollowUpItem,
  Report,
  ActivityItem,
  ChartData,
  SparklineData,
} from './types';

// --- Utility Functions ---
function getPastDate(daysAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
}

function getFutureDate(daysFromNow: number): string {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString();
}

const currentISODate = new Date().toISOString();

// --- Demo User ---
export const DEMO_USER: DemoUser = {
  id: 'usr_12345',
  name: 'Eleanor Vance',
  email: 'eleanor.vance@wellnessclinic.com',
  role: 'Clinic Owner',
  plan: 'Pro',
  avatar: 'EV',
  joinedAt: getPastDate(365),
};

// --- Mock Data: Clinics ---
export const MOCK_CLINICS: Clinic[] = [
  {
    id: 'cln_001',
    userId: DEMO_USER.id,
    name: 'Serene Health & Wellness',
    address: '123 Tranquil Lane, Suite 100, Cityville, CA 90210',
    phone: '(555) 123-4567',
    email: 'info@serenehealth.com',
    status: 'active',
    createdAt: getPastDate(300),
    updatedAt: getPastDate(5),
  },
  {
    id: 'cln_002',
    userId: DEMO_USER.id,
    name: 'Vitality Wellness Center',
    address: '456 Energy Drive, Unit 201, Townsville, TX 75001',
    phone: '(555) 987-6543',
    email: 'contact@vitalitywc.com',
    status: 'active',
    createdAt: getPastDate(250),
    updatedAt: getPastDate(10),
  },
  {
    id: 'cln_003',
    userId: DEMO_USER.id,
    name: 'Harmony Healing Clinic',
    address: '789 Peace Avenue, Office 300, Villageton, NY 10001',
    phone: '(555) 234-5678',
    email: 'admin@harmonyhealing.com',
    status: 'inactive',
    createdAt: getPastDate(180),
    updatedAt: getPastDate(60),
  },
];

// --- Mock Data: Clients ---
export const MOCK_CLIENTS: Client[] = [
  {
    id: 'cli_101',
    clinicId: MOCK_CLINICS[0].id,
    userId: DEMO_USER.id,
    name: 'Marcus Thorne',
    email: 'marcus.thorne@example.com',
    phone: '(555) 111-2222',
    notes: 'Primary focus: Stress reduction & sleep improvement.',
    status: 'active',
    createdAt: getPastDate(120),
    updatedAt: getPastDate(3),
  },
  {
    id: 'cli_102',
    clinicId: MOCK_CLINICS[0].id,
    userId: DEMO_USER.id,
    name: 'Sophia Chang',
    email: 'sophia.c@example.com',
    phone: '(555) 333-4444',
    notes: 'Requires regular check-ins for dietary adjustments.',
    status: 'active',
    createdAt: getPastDate(90),
    updatedAt: getPastDate(1),
  },
  {
    id: 'cli_103',
    clinicId: MOCK_CLINICS[0].id,
    userId: DEMO_USER.id,
    name: 'David Lee',
    email: 'david.lee@example.com',
    phone: '(555) 555-6666',
    notes: 'Interested in advanced pain management techniques.',
    status: 'inactive',
    createdAt: getPastDate(150),
    updatedAt: getPastDate(30),
  },
  {
    id: 'cli_104',
    clinicId: MOCK_CLINICS[1].id,
    userId: DEMO_USER.id,
    name: 'Olivia Rodriguez',
    email: 'olivia.r@example.com',
    phone: '(555) 777-8888',
    notes: 'New client, initial consultation scheduled for next week.',
    status: 'prospect',
    createdAt: getPastDate(10),
    updatedAt: getPastDate(1),
  },
  {
    id: 'cli_105',
    clinicId: MOCK_CLINICS[1].id,
    userId: DEMO_USER.id,
    name: 'Ethan Kim',
    email: 'ethan.k@example.com',
    phone: '(555) 999-0000',
    notes: 'Has specific physical therapy follow-ups.',
    status: 'active',
    createdAt: getPastDate(60),
    updatedAt: getPastDate(2),
  },
  {
    id: 'cli_106',
    clinicId: MOCK_CLINICS[0].id,
    userId: DEMO_USER.id,
    name: 'Isabella Garcia',
    email: 'isabella.g@example.com',
    phone: '(555) 121-3434',
    notes: 'Recently completed a wellness program, due for a re-booking reminder.',
    status: 'active',
    createdAt: getPastDate(45),
    updatedAt: getPastDate(7),
  },
  {
    id: 'cli_107',
    clinicId: MOCK_CLINICS[0].id,
    userId: DEMO_USER.id,
    name: 'Liam Chen',
    email: 'liam.c@example.com',
    phone: '(555) 565-7878',
    notes: 'Follow-up for post-procedure check-in.',
    status: 'active',
    createdAt: getPastDate(20),
    updatedAt: getPastDate(0),
  },
  {
    id: 'cli_108',
    clinicId: MOCK_CLINICS[1].id,
    userId: DEMO_USER.id,
    name: 'Ava Martinez',
    email: 'ava.m@example.com',
    phone: '(555) 909-1212',
    notes: 'Interested in advanced nutrition counseling.',
    status: 'prospect',
    createdAt: getPastDate(5),
    updatedAt: getPastDate(0),
  },
  {
    id: 'cli_109',
    clinicId: MOCK_CLINICS[0].id,
    userId: DEMO_USER.id,
    name: 'Noah Wilson',
    email: 'noah.w@example.com',
    phone: '(555) 343-5656',
    notes: 'Chronic pain management, requires ongoing consultation.',
    status: 'active',
    createdAt: getPastDate(180),
    updatedAt: getPastDate(14),
  },
  {
    id: 'cli_110',
    clinicId: MOCK_CLINICS[1].id,
    userId: DEMO_USER.id,
    name: 'Mia Taylor',
    email: 'mia.t@example.com',
    phone: '(555) 787-9090',
    notes: 'Requires a follow-up for a recent health scare.',
    status: 'active',
    createdAt: getPastDate(30),
    updatedAt: getPastDate(4),
  },
];

// --- Mock Data: FollowUpItems ---
export const MOCK_FOLLOW_UP_ITEMS: FollowUpItem[] = [
  {
    id: 'fui_001',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[0].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[0].name,
    clientContact: MOCK_CLIENTS[0].email,
    followUpType: 'Re-booking',
    urgency: 'High',
    dueDate: getFutureDate(3),
    notes: 'Client expressed interest in scheduling next session. Follow up by phone.',
    status: 'Pending',
    createdAt: getPastDate(2),
    updatedAt: currentISODate,
  },
  {
    id: 'fui_002',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[1].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[1].name,
    clientContact: MOCK_CLIENTS[1].phone,
    followUpType: 'Check-in',
    urgency: 'Medium',
    dueDate: getFutureDate(7),
    notes: 'Monitor progress on new dietary plan. Send quick email.',
    status: 'Pending',
    createdAt: getPastDate(5),
    updatedAt: getPastDate(1),
  },
  {
    id: 'fui_003',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[2].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[2].name,
    clientContact: MOCK_CLIENTS[2].email,
    followUpType: 'Consultation',
    urgency: 'Low',
    dueDate: getFutureDate(14),
    notes: 'Send information on upcoming pain management workshop.',
    status: 'Pending',
    createdAt: getPastDate(10),
    updatedAt: getPastDate(5),
  },
  {
    id: 'fui_004',
    clinicId: MOCK_CLINICS[1].id,
    clientId: MOCK_CLIENTS[3].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[3].name,
    clientContact: MOCK_CLIENTS[3].email,
    followUpType: 'Reminder',
    urgency: 'Critical',
    dueDate: getFutureDate(1),
    notes: 'Initial consultation tomorrow. Send final reminder and pre-visit form link.',
    status: 'Pending',
    createdAt: getPastDate(1),
    updatedAt: currentISODate,
  },
  {
    id: 'fui_005',
    clinicId: MOCK_CLINICS[1].id,
    clientId: MOCK_CLIENTS[4].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[4].name,
    clientContact: MOCK_CLIENTS[4].phone,
    followUpType: 'Other',
    urgency: 'Medium',
    dueDate: getFutureDate(5),
    notes: 'Special request for physical therapy exercise video links. Email resources.',
    status: 'Completed',
    createdAt: getPastDate(8),
    updatedAt: getPastDate(3),
  },
  {
    id: 'fui_006',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[5].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[5].name,
    clientContact: MOCK_CLIENTS[5].email,
    followUpType: 'Re-booking',
    urgency: 'High',
    dueDate: getFutureDate(4),
    notes: 'Program finished last week. Suggest re-booking next phase.',
    status: 'Pending',
    createdAt: getPastDate(3),
    updatedAt: getPastDate(0),
  },
  {
    id: 'fui_007',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[6].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[6].name,
    clientContact: MOCK_CLIENTS[6].phone,
    followUpType: 'Check-in',
    urgency: 'Critical',
    dueDate: getPastDate(0), // Today
    notes: 'Post-procedure check-in call required by end of day.',
    status: 'Pending',
    createdAt: getPastDate(1),
    updatedAt: currentISODate,
  },
  {
    id: 'fui_008',
    clinicId: MOCK_CLINICS[1].id,
    clientId: MOCK_CLIENTS[7].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[7].name,
    clientContact: MOCK_CLIENTS[7].email,
    followUpType: 'Consultation',
    urgency: 'Medium',
    dueDate: getFutureDate(21),
    notes: 'Schedule discovery call for nutrition counseling.',
    status: 'Pending',
    createdAt: getPastDate(7),
    updatedAt: getPastDate(2),
  },
  {
    id: 'fui_009',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[8].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[8].name,
    clientContact: MOCK_CLIENTS[8].phone,
    followUpType: 'Other',
    urgency: 'Low',
    dueDate: getFutureDate(28),
    notes: 'Send latest article on chronic pain management techniques.',
    status: 'Archived',
    createdAt: getPastDate(30),
    updatedAt: getPastDate(15),
  },
  {
    id: 'fui_010',
    clinicId: MOCK_CLINICS[1].id,
    clientId: MOCK_CLIENTS[9].id,
    userId: DEMO_USER.id,
    clientName: MOCK_CLIENTS[9].name,
    clientContact: MOCK_CLIENTS[9].email,
    followUpType: 'Check-in',
    urgency: 'High',
    dueDate: getFutureDate(2),
    notes: 'Client expressed concerns during last visit. Urgent follow up needed.',
    status: 'Pending',
    createdAt: getPastDate(0),
    updatedAt: currentISODate,
  },
];

// --- Mock Data: Reports ---
export const MOCK_REPORTS: Report[] = [
  {
    id: 'rpt_001',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[0].id,
    userId: DEMO_USER.id,
    title: 'Client Progress Report - Marcus Thorne (Q1 2024)',
    generatedAt: getPastDate(30),
    reportContent: 'Summary of wellness goals achieved and next steps for stress reduction.',
    status: 'sent',
    createdAt: getPastDate(35),
    updatedAt: getPastDate(30),
  },
  {
    id: 'rpt_002',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[1].id,
    userId: DEMO_USER.id,
    title: 'Dietary Plan Review - Sophia Chang (May 2024)',
    generatedAt: getPastDate(10),
    reportContent: 'Detailed analysis of dietary intake and recommendations for adjustment.',
    status: 'generated',
    createdAt: getPastDate(12),
    updatedAt: getPastDate(10),
  },
  {
    id: 'rpt_003',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[2].id,
    userId: DEMO_USER.id,
    title: 'Pain Management Plan - David Lee (Initial Assessment)',
    generatedAt: getPastDate(60),
    reportContent: 'Overview of initial assessment and proposed treatment plan for chronic pain.',
    status: 'sent',
    createdAt: getPastDate(65),
    updatedAt: getPastDate(60),
  },
  {
    id: 'rpt_004',
    clinicId: MOCK_CLINICS[1].id,
    clientId: MOCK_CLIENTS[3].id,
    userId: DEMO_USER.id,
    title: 'New Client Intake Summary - Olivia Rodriguez',
    generatedAt: getPastDate(1),
    reportContent: 'Summary of initial client intake, health history, and primary concerns.',
    status: 'draft',
    createdAt: getPastDate(2),
    updatedAt: getPastDate(1),
  },
  {
    id: 'rpt_005',
    clinicId: MOCK_CLINICS[1].id,
    clientId: MOCK_CLIENTS[4].id,
    userId: DEMO_USER.id,
    title: 'Physical Therapy Progress - Ethan Kim (April 2024)',
    generatedAt: getPastDate(20),
    reportContent: 'Progress tracking for physical therapy exercises and mobility improvements.',
    status: 'sent',
    createdAt: getPastDate(25),
    updatedAt: getPastDate(20),
  },
  {
    id: 'rpt_006',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[5].id,
    userId: DEMO_USER.id,
    title: 'Wellness Program Completion - Isabella Garcia',
    generatedAt: getPastDate(7),
    reportContent: 'Certificate of completion for wellness program and recommendations for next steps.',
    status: 'generated',
    createdAt: getPastDate(8),
    updatedAt: getPastDate(7),
  },
  {
    id: 'rpt_007',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[6].id,
    userId: DEMO_USER.id,
    title: 'Post-Procedure Care Plan - Liam Chen',
    generatedAt: getPastDate(1),
    reportContent: 'Detailed instructions for post-procedure care and recovery.',
    status: 'sent',
    createdAt: getPastDate(2),
    updatedAt: getPastDate(1),
  },
  {
    id: 'rpt_008',
    clinicId: MOCK_CLINICS[1].id,
    clientId: MOCK_CLIENTS[7].id,
    userId: DEMO_USER.id,
    title: 'Nutrition Counseling Proposal - Ava Martinez',
    generatedAt: getPastDate(5),
    reportContent: 'Proposal for a personalized nutrition counseling program.',
    status: 'draft',
    createdAt: getPastDate(6),
    updatedAt: getPastDate(5),
  },
  {
    id: 'rpt_009',
    clinicId: MOCK_CLINICS[0].id,
    clientId: MOCK_CLIENTS[8].id,
    userId: DEMO_USER.id,
    title: 'Chronic Pain Management Review - Noah Wilson (June 2024)',
    generatedAt: getPastDate(15),
    reportContent: 'Review of current pain management strategies and adjustments.',
    status: 'sent',
    createdAt: getPastDate(18),
    updatedAt: getPastDate(15),
  },
  {
    id: 'rpt_010',
    clinicId: MOCK_CLINICS[1].id,
    clientId: MOCK_CLIENTS[9].id,
    userId: DEMO_USER.id,
    title: 'Emergency Health Event Follow-up - Mia Taylor',
    generatedAt: getPastDate(4),
    reportContent: 'Summary of recent health event and immediate follow-up actions.',
    status: 'generated',
    createdAt: getPastDate(5),
    updatedAt: getPastDate(4),
  },
];

// --- Key Performance Indicator Stats ---
export const STATS = {
  totalFollowUps: 112,
  pendingFollowUps: 28,
  completedThisWeek: 15,
  newClientsThisMonth: 8,
  revenueLastMonth: '$12,450',
  clientRetentionRate: '88%',
};

// --- Chart Data ---
export const CHART_DATA: ChartData = {
  weeklyFollowUps: [65, 72, 58, 80, 75, 92, 88, 70, 95, 105, 98, 112],
  labels: [
    'Jan W1', 'Jan W2', 'Jan W3', 'Jan W4', 'Feb W1', 'Feb W2',
    'Feb W3', 'Feb W4', 'Mar W1', 'Mar W2', 'Mar W3', 'Mar W4',
  ],
  revenue: [
    18200, 22400, 19800, 31200, 25600, 28900, 23500, 34100, 29800, 36500, 32100,
    38700,
  ], // Example, not directly used in this MVP, but good for dashboard context.
};

// --- Sparkline Data for StatCards ---
export const SPARKLINE_DATA: SparklineData = {
  totalFollowUps: [80, 85, 78, 92, 88, 95, 102],
  pendingFollowUps: [35, 32, 38, 30, 28, 25, 22],
  completedThisWeek: [8, 10, 7, 12, 11, 15, 13],
  newClientsThisMonth: [1, 2, 3, 5, 4, 6, 8],
  revenueLastMonth: [10200, 10800, 11500, 11000, 12000, 12450, 13000],
  clientRetentionRate: [85, 86, 87, 86, 88, 87, 89],
};

// --- Recent Activity ---
export const RECENT_ACTIVITY: ActivityItem[] = [
  {
    id: 'act_001',
    action: 'Created new follow-up for Marcus Thorne',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '2 minutes ago',
    type: 'create',
  },
  {
    id: 'act_002',
    action: 'Marked Sophia Chang check-in as completed',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '1 hour ago',
    type: 'update',
  },
  {
    id: 'act_003',
    action: 'Generated Client Progress Report for Isabella Garcia',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '3 hours ago',
    type: 'generate',
  },
  {
    id: 'act_004',
    action: 'Archived old follow-up for David Lee',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: 'Yesterday',
    type: 'archive',
  },
  {
    id: 'act_005',
    action: 'Added new client Olivia Rodriguez',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '2 days ago',
    type: 'create',
  },
  {
    id: 'act_006',
    action: 'Updated due date for Ethan Kim\'s follow-up',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '3 days ago',
    type: 'update',
  },
  {
    id: 'act_007',
    action: 'Created new follow-up for Mia Taylor (Critical Urgency)',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '4 days ago',
    type: 'create',
  },
  {
    id: 'act_008',
    action: 'Sent Post-Procedure Care Plan to Liam Chen',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '5 days ago',
    type: 'send',
  },
  {
    id: 'act_009',
    action: 'Marked Ava Martinez consultation as pending',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '1 week ago',
    type: 'update',
  },
  {
    id: 'act_010',
    action: 'Generated New Client Intake Summary for Olivia Rodriguez',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '1 week ago',
    type: 'generate',
  },
  {
    id: 'act_011',
    action: 'Archived follow-up item for Noah Wilson',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '2 weeks ago',
    type: 'archive',
  },
  {
    id: 'act_012',
    action: 'Created new clinic "Vitality Wellness Center"',
    user: 'Eleanor Vance',
    avatar: 'EV',
    time: '1 month ago',
    type: 'create',
  },
];

// --- Helper function to get an item by ID ---
export function getById<T extends { id: string }>(
  arr: T[],
  id: string,
): T | undefined {
  return arr.find((x) => x.id === id);
}